apisix:
  node_listen: 9080
  enable_admin: true
  admin_listen:
    ip: 0.0.0.0
    port: 9180
  admin_key:
    - name: "admin"
      key: "admin"
      role: admin
  config_center: etcd

etcd:
  host:
    - "http://etcd:2379"
  prefix: "/apisix"
